# https://www.squid-cache.org/Doc/config/

# General ---

http_port 3128 ssl-bump \
  cert=/ca/mitm-proxy.crt key=/ca/mitm-proxy.key \
  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB

sslcrtd_program /usr/lib/squid/security_file_certgen -s /var/cache/squid/ssl_db -M 16MB

logfile_rotate 0
cache_log stdio:/dev/stdout
access_log stdio:/dev/stdout
cache_store_log stdio:/dev/stdout
pid_filename /var/run/squid/squid.pid
client_request_buffer_max_size 100 MB

cache_effective_user squid
cache_effective_group squid
