# ACL ---

acl SafePorts port 80
acl SafePorts port 443

acl SSLPorts port 443

# https://code.claude.com/docs/en/network-config#network-access-requirements
acl AllowedDomains dstdomain \
  .api.anthropic.com \
  .chatgpt.com \
  .claude.ai \
  .deb.debian.org \
  .openai.com \
  .platform.claude.com \
  .raw.githubusercontent.com \
  .visualstudio.com
